sudo: false
language: python
python:
  - "3.4"

cache: false

install:
  - pip install coveralls
  - pip install twine
  - pip install whitenoise
  - pip install django-environ
  - pip install django-rest-auth[with_social]
  - pip install -e .

addons:
  sonarcloud:
    organization: "vandorjw-github"
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $GITHUB_TOKEN

script:
  - coverage run `which django-admin.py` test
  - sonar-scanner

notifications:
  email: false

branches:
  only:
    - master

after_success:
  - coveralls
