sudo: false
language: python
python:
  - "3.4"

cache: false

install:
  - pip install coveralls
  - pip install -e .

addons:
  sonarqube:
    token:
      secure: $SONAR_TOKEN

script:
  - coverage run `which django-admin.py` test
  - sonar-scanner

notifications:
  email: false

branches:
  only:
    - master

after_success:
  - coveralls
