sudo: false
language: python
python:
  - "3.4"

cache: false

install:
  - pip install -e .

script:
  - django-admin test

notifications:
  email: false

branches:
  only:
    - master
    - development
