sudo: false
language: python
python:
  - "3.4"

cache: false

install:
  - pip install coveralls
  - pip install -e .

script:
  - coverage run `which django-admin.py` test

notifications:
  email: false

branches:
  only:
    - master
    - development

after_success:
  - coveralls