apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: django-assessment-ingress
spec:
  rules:
  - host: api.assessment.localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: django-assessment-service
          servicePort: 5000
