kind: Service
apiVersion: v1
metadata:
  name: django-assessment-service
spec:
  selector:
    app: django-assessment
  ports:
    - name: assessment-api
      protocol: TCP
      port: 5000
      targetPort: 5000
  externalIPs:
    - 192.168.1.233

